[peakvalley]
BatNum = 1
BatMaxCapacity = 5
BatChgMaxMultiplier = 1.5
BatDisMaxMultiplier = 2.5
BatSocMin = 0.1
HrMin = 0.5
SellDiscount = 0.12
SpikeLevel = 300
SolarCharge = 0
SellBack = 0
BuyPct = 50
SellPct = 1
PeakPct = 70
PeakPrice = 1000
LookBackDays = 1
SampleInterval = 120
ChgStart1 = "06:00"
ChgEnd1 = "16:00"
DisChgStart2 = "17:00"
DisChgEnd2 = "23:55"
DisChgStart1 = "00:00"
DisChgEnd1 = "08:00"
DisChgStartTest= "17:00"
DisChgEndTest = "23:55"
PeakStart = "18:00"
PeakEnd = "20:00"
[shawsbay]
SampleInterval = 900
[battery_types]
011LOKG080015B = 5000
011LOKL140058B = 5000
011LOKL140104B = 5000
RX7000PLUS254F313532 = 7000
[battery_locations]
011LOKG080015B = 'qld'
011LOKL140058B = 'qld'
RX2505ACA10J0A180003 = 'qld'
RX2505ACA10J0A160016 = 'qld'
011LOKL140104B = 'nsw'
[battery_retailers]
011LOKG080015B = 'lv'
011LOKL140058B = 'lv'
RX2505ACA10J0A180003 = 'lv'
RX2505ACA10J0A160016 = 'lv'
011LOKL140104B = 'amber'
RX2505ACA10JOA160037 = 'lv'
RX2505ACA10J0A160010 = 'lv'
[battery_algo_types]
011LOKL140058B = 'sell_to_grid'
RX2505ACA10J0A180003 = 'sell_to_grid'
RX2505ACA10J0A160016 = 'sell_to_grid'
011LOKL140104B = 'cover_usage'
[apikey_varnames]
apikey_varname_qld = 'API_AMBER_QLD'
apikey_varname_nsw = 'API_AMBER_NSW'
[apiurls]
apiurl_qld = 'https://api.amber.com.au/v1/sites/01HDN4PXKQ1MR29SWJPHBQE8M8/prices/current?next=0&previous=0&resolution=30'
apiurl_nsw = 'https://api.amber.com.au/v1/sites/01HRDW17W9MVRM5PZCD5CNM0X6/prices/current?next=0&previous=0&resolution=30'

